# Generated by Django 3.2.19 on 2023-09-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant_activities_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restraurant',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='point',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='point',
            new_name='points',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurant',
        ),
    ]
