# Generated by Django 3.2.19 on 2023-10-03 09:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant_activities_management', '0003_auto_20230930_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award_code', models.PositiveIntegerField(max_length=4)),
                ('code_used_state', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restraurant_activities_management.award')),
            ],
            options={
                'db_table': 'awardcount',
            },
        ),
    ]
