# Generated by Django 3.2.19 on 2023-10-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20230928_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_points_made',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
